name: build docs

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

permissions:
  contents: write

jobs:
  builddocs:
    runs-on: ubuntu-latest
    env:
      UPLOAD_TO_GHPAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      SPHINX_WARNINGS_AS_ERROR: true
      SPHINX_OPTS: "-v"

    steps:
      - uses: actions/checkout@v4
        with:
          # we need full history with tags for the version number
          fetch-depth: 0

      - name: set-sphinx-opts
        run: echo "SPHINX_OPTS=-W -v" >> $GITHUB_ENV

      - name: install pandoc linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update || true
          sudo apt install -y pandoc

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            requirements.txt

      - name: Install dependencies and package
        uses: ./.github/actions/install-dependencies-and-booksai

      - name: Build docs
        run: |
          cd docs
          make html

      - name: Upload build docs
        uses: actions/upload-artifact@v4
        with:
          name: docs_ubuntu
          path: ${{ github.workspace }}/docs/_build/html

      - name: Deploy to gh pages
        if: ${{ fromJSON(env.UPLOAD_TO_GHPAGES) }}
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: ${{ github.workspace }}/docs/_build/html
          clean: true
          single-commit: true
          git-config-email: "bot"
          git-config-name: "Documentation Bot"
